spring:
  application:
    name: partnerflow-crm

  datasource:
    url: jdbc:postgresql://localhost:5433/partnerflow_db
    username: partnerflow_user
    password: partnerflow_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always